apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  labels:
    {{- include "dawn-treader.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: dawn-treader-redirect-https@kubernetescrd
spec:
  tls:
  - hosts:
    - localhost
    secretName: mrlouf-studio-tls
  rules:
  - host: localhost
    http:
      paths:
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3100
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3100
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 5173