global:
  domain: gitea.localhost

service:
  ssh:
    type: NodePort
    port: 2222
    nodePort: 30022

persistence:
  enabled: true
  existingClaim: gitea-pvc

ingress:
  enabled: true
  pathType: Prefix
  hosts:
    - host: gitea.localhost
      paths:
        - path: /

configs:
  params:
    server.insecure: true

valkey-cluster:
  enabled: false
valkey:
  enabled: true
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true

gitea:
  config:
    database:
      DB_TYPE: postgres

    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true

    server:
      SSH_DOMAIN: gitea.localhost
      SSH_PORT: 30022
      START_SSH_SERVER: true

